apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-api
  template:
    metadata:
      labels:
        app: auth-api
    spec:
      containers:
        - name: auth-api
          image: tejirih/auth-image:latest
          ports:
            - containerPort: 8081
          env:
            - name: AUTH_API_PORT
              value: "8081"
            - name: USERS_API_ADDRESS  # 👈 Ensure this points to users-api
              value: "http://users-api:8083"  
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_SECRET


