apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: users-api
  template:
    metadata:
      labels:
        app: users-api
    spec:
      containers:
      - name: users-api
        image: tejirih/users-image:latest
        ports:
        - containerPort: 8083
        env:
        - name: SERVER_PORT
          value: "8083"
