apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-api
  labels:
    app: auth-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-api
  template:
    metadata:
      labels:
        app: auth-api
    spec:
      containers:
      - name: auth-api
        image: tejirih/auth-image:latest
        ports:
        - containerPort: 8081
        env:
        - name: AUTH_API_PORT
          value: "8081"  # Ensure this is set correctly
        - name: REDIS_HOST
          value: "redis"  # Redis service name
        - name: REDIS_PORT
          value: "6379"  # Ensure it's the correct port

